# Homework

## Q1. Pandas Version

In [1]:
import pandas as pd
pd.__version__

'2.3.2'

- get data

In [2]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-10-03 12:10:00--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.2’

car_fuel_efficiency 100%[===================>] 853.70K  4.12MB/s    in 0.2s    

2025-10-03 12:10:01 (4.12 MB/s) - ‘car_fuel_efficiency.csv.2’ saved [874188/874188]



In [3]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [4]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

---

## Q2. Records count

In [5]:
len(df), df.shape

(9704, (9704, 11))

---

## Q3. Fuel types

In [6]:
df.fuel_type.nunique()

2

In [7]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

---

## Q4. Missing Values

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

---

## Q5. Max fuel efficiency

In [9]:
filtered_df = df[df["origin"] == "Asia"]

In [10]:
filtered_df.fuel_efficiency_mpg.max()

23.759122836520497

In [11]:
filtered_df.sort_values(by="fuel_efficiency_mpg", ascending=False).head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9387                  330            3.0       136.0     1223.298226   
343                   240            2.0         NaN     1652.883753   
7739                  170           10.0       139.0     1491.755825   
9401                  110            1.0       183.0     1707.231276   
5416                  250            6.0       173.0     1354.787120   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9387           NaN        2001   Asia  Gasoline  Front-wheel drive        1.0   
343           11.0        2018   Asia  Gasoline  Front-wheel drive        0.0   
7739          13.0        2005   Asia    Diesel  Front-wheel drive        0.0   
9401          11.9        2018   Asia    Diesel    All-wheel drive       -1.0   
5416          17.3        2007   Asia  Gasoline  Front-wheel drive        0.0   

      fuel_efficiency_mpg  
9387            23.759123  
343             23.204566  
7739            23.033673  
9401            22.919968  
5416            22.858156

In [12]:
filtered_df.fuel_efficiency_mpg.sort_values(ascending=False).head(5)

9387    23.759123
343     23.204566
7739    23.033673
9401    22.919968
5416    22.858156
Name: fuel_efficiency_mpg, dtype: float64

---

## Q6. Median value of horsepower

In [32]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [33]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

esta la tuve mal, por que no hice el "inplace" y tal vez me confié de más, ya que no hice la validación

In [ ]:
df['horsepower'] = df['horsepower'].fillna(152)

# también pudo hacerse asi:
# df.horsepower.fillna(152, inplace=True)


In [35]:
df.horsepower.median()

152.0

In [36]:
df.horsepower.describe()

count    9704.000000
mean      149.828215
std        28.775248
min        37.000000
25%       131.000000
50%       152.000000
75%       168.000000
max       271.000000
Name: horsepower, dtype: float64

---

## Q7. Sum of weights

In [18]:
asian_cars = df[df["origin"] == "Asia"]

In [19]:
asian_cars = asian_cars[["vehicle_weight","model_year"]].head(7)

In [20]:
import numpy as np

In [21]:
X = np.array(asian_cars)

In [22]:
# X = asian_cars.to_numpy()

In [23]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [24]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [25]:
XTX = np.dot(X.T, X)

In [26]:
XTX_inv = np.linalg.inv(XTX)

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [28]:
Z = np.dot(XTX_inv,X.T)

In [29]:
w = np.dot(Z,y)

In [30]:
w

array([0.01386421, 0.5049067 ])

In [31]:
w.sum()

np.float64(0.5187709081074002)