# Homework

## Q1. Pandas Version

In [2]:
import pandas as pd
pd.__version__

'2.3.2'

- get data

In [3]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-28 09:09:37--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  2.54MB/s    in 0.3s    

2025-09-28 09:09:38 (2.54 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [7]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [8]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

---

## Q2. Records count

In [6]:
len(df), df.shape

(9704, (9704, 11))

---

## Q3. Fuel types

In [9]:
df.fuel_type.nunique()

2

In [11]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

---

## Q4. Missing Values

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

---

## Q5. Max fuel efficiency

In [13]:
df.fuel_efficiency_mpg.max()

25.96722204888372

In [22]:
df.sort_values(by="fuel_efficiency_mpg", ascending=False).head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
5014                  210            3.0       206.0      952.681761   
5815                  180            2.0       188.0     1066.328301   
9387                  330            3.0       136.0     1223.298226   
560                   240            5.0       151.0     1314.839625   
8300                  140            2.0       113.0     1336.444231   

      acceleration  model_year  origin fuel_type         drivetrain  \
5014          18.5        2015  Europe  Gasoline  Front-wheel drive   
5815           NaN        2013     USA  Gasoline  Front-wheel drive   
9387           NaN        2001    Asia  Gasoline  Front-wheel drive   
560           15.0        2012     USA  Gasoline  Front-wheel drive   
8300          16.2        2015  Europe    Diesel  Front-wheel drive   

      num_doors  fuel_efficiency_mpg  
5014       -1.0            25.967222  
5815        2.0            24.971452  
9387        1.0            23.759123  
560         0.0            23.556075  
8300        1.0            23.369176

In [21]:
df.fuel_efficiency_mpg.sort_values(ascending=False).head(5)

5014    25.967222
5815    24.971452
9387    23.759123
560     23.556075
8300    23.369176
Name: fuel_efficiency_mpg, dtype: float64

---

## Q6. Median value of horsepower

In [23]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [24]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [25]:
df.horsepower.fillna(152)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [26]:
df.horsepower.median()

149.0

In [28]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

---

## Q7. Sum of weights

In [55]:
asian_cars = df[df["origin"] == "Asia"]

In [56]:
asian_cars = asian_cars[["vehicle_weight","model_year"]].head(7)

In [57]:
import numpy as np

In [58]:
X = np.array(asian_cars)

In [59]:
# X = asian_cars.to_numpy()

In [60]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [61]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [63]:
XTX = np.dot(X.T, X)

In [64]:
XTX_inv = np.linalg.inv(XTX)

In [65]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [66]:
Z = np.dot(XTX_inv,X.T)

In [67]:
w = np.dot(Z,y)

In [68]:
w

array([0.01386421, 0.5049067 ])

In [69]:
w.sum()

np.float64(0.5187709081074002)